### ISSUE TITLE
Use <nav> for site navigation

### ISSUE THREAD

**Issue by develowlper** [hello-sunshine-dot-dev/hello-sunshine#1]
Herzlich willkommen bei deinem ersten Git-Issue.

Mit Git-Issues kann man Bugs tracken, Features planen usw. Es ist zwar nur ein etwas bessere Ticketsystem aber richtig genutzt kann es einem viel abnehmen. Und hier kommt dein erstes issue:

Die Navigation  ist bisher nur eine Liste von <a>-Tags. HTML bietet für Navigation allerdings ein fancy <nav>-Tag (https://www.w3schools.com/TAgs/tag_nav.asp). Vielleicht kannst du das nutzen um deine Seite etwas zu pimpen und es Menschen mit Screenreadern vereinfachen deine Seite zu genießen.

**Comment by choss86** [comment]
Ich habe das nav-Tag jetzt eingefügt.
