### ISSUE TITLE
Style navigation

### ISSUE THREAD

**Issue by develowlper** [hello-sunshine-dot-dev/hello-sunshine#3]
So da tailwind jetzt am Start ist, kannst du direkt die Navigation ein wenig fancy machen. 

Eventuell findest du auf der tailwind-Seite auch einige Hinweise wie das funktioniert. 

Happy Coding.

**Comment by develowlper** [comment]
@choss86 PS: Wenn du kein Bock hast, die Issue immer manuell zu closen, dann schau mal hier: https://github.blog/2013-01-22-closing-issues-via-commit-messages/

**Comment by choss86** [comment]
Gibt es eine Möglichkeit, die Styles für alle Seiten anzuwenden (z.B. Navi und Body)? Oder muss ich die Klassen auf jeder Unterseite manuell einfügen?

**Comment by develowlper** [comment]
Aktuell musst du die Styles für jede Seite einzeln machen. Am besten einfach copy & paste. 
Wenn du Sachen für alle Navs oder so machen willst, musst du eigenes CSS schreiben.

Wie man geschickt Componenten wie ne Navi baut, die man mehrmals einsetzen kann, kommt später. :)
